version: "3.8"
services:
  app:
    container_name: finalwork-app
    build:
      context: ./
      dockerfile: Dockerfile # The name of the Dockerfile relative to the context path
    image: finalwork/finalwork:latest # (Optional but recommended) Names the resulting ima
    environment:
      DB_HOST: "finalwork-postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "finalwork"
      DB_PORT: 5432
      SECRET_KEY: "you_can_add_on_here_secret_key"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - finalwork-network

  prometheus:
    container_name: finalwork-prometheus
    image: prom/prometheus
    volumes:
      - .\prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - finalwork-network

  grafana:
    container_name: finalwork-grafana
    image: grafana/grafana-enterprise # Use the official Grafana image
    restart: unless-stopped
    ports:
      - "3000:3000" # Expose Grafana on host port 3000
    volumes:
      - grafana-data:/var/lib/grafana # Persist data in a named volume
    networks:
      - finalwork-network

  postgres:
    container_name: finalwork-postgres
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - finalwork-network

  pgadmin:
    container_name: finalwork-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "kurbangaliev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - finalwork-network

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  pgadmin-data:
    driver: local
  db-data:
    driver: local

networks:
  finalwork-network:
    driver: bridge
